# Generated by Django 4.1 on 2023-07-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('first_name', models.CharField(blank=True, default='unknown', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='unknown', max_length=55)),
                ('last_name', models.CharField(default='unknown', max_length=55)),
                ('subject', models.CharField(default='marathi', max_length=55)),
                ('age', models.IntegerField(default=19)),
            ],
        ),
    ]
