# Generated by Django 4.1 on 2023-07-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('subject', models.CharField(default='Unknown', max_length=55)),
                ('time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_complete', models.BooleanField(default=True)),
            ],
        ),
    ]
