# Generated by Django 4.1 on 2023-07-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0002_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='message',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
